
#all these don't actually disable blocks anymore, they just remove their recipe and remove them from the creative tabs(like all other mods do)
#to access server configuration go into /saves/serverconfigs
[general]
	#enable creative tab
	creative_tab = false
	#set to false to disable custom dispenser behaviors (filling jars) if for some reason they are causing trouble
	dispensers = false
	#creates a creative tab full of filled jars
	jar_tab = false

#Enable and disable blocks / entities
[registration]

	[registration.entities]
		firefly = true

	[registration.blocks]
		clock_block = true
		speaker_block = true
		sack = false
		#WIP
		laser_block = false
		bellows = false
		hanging_sign = true
		bomb = true
		cage = true
		bamboo_spikes = false
		hourglass = false
		jar = false
		sconce_ender = true
		rope_arrow = false
		checker_block = true
		stone_lamp = true
		cog_block = false
		crank = true
		copper_lantern = true
		pancake = false
		piston_launcher = false
		netherite_trapdoor = false
		fodder = true
		globe = true
		sconce = true
		candelabra = true
		safe = false
		sconce_lever = true
		sign_post = true
		pedestal = true
		blackboard = true
		netherite_door = false
		sconce_soul = true
		candle_holder = true
		#WIP
		flag = false
		rope = false
		notice_board = true
		redstone_illuminator = true
		lock_block = false
		flax = false
		planter = true
		wind_vane = true
		item_shelf = true
		turn_table = false
		faucet = false
		gold_trapdoor = false
		magma_cream_block = true
		sconce_green = false
		flute = true
		pulley_block = false
		gold_door = false

